Cherrypy salt blog
terminal-labs/tl_web pull request #44
Opened 2022-08-03 19:42 UTC by BenjaminEchelmeier

Draft of "A Salty API"

2022-08-05 17:06 UTC, alan-cugler requested changes

2022-08-05 19:18 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +author: Mike Pinna
I am working on adding myself as an editor. Have to figure out this whole submodule thing to do so, cause the changes need to happen in the theme.

2022-08-05 20:03 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +The normal workflow for executing salt commands involves an SSH session into a salt master. This, however, grows cumbersome when automating salt commands from an outside source such as a remote web s
What do you mean by "move cherrypy line to the rest_cherrypy implementation section."?
I'm not sure which line you're referring to.

2022-08-05 20:04 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +The normal workflow for executing salt commands involves an SSH session into a salt master. This, however, grows cumbersome when automating salt commands from an outside source such as a remote web s
@Pinna3 you might be able to provide more insight than my salt-novice self on a real-world scenario.

2022-08-05 20:23 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +$ ssh -i ~/.ssh/<RSA_KEY> ubuntu@<saltmaster_hostname>
I like leaving some variables like this in a tutorial, as it can keep clear what should be changeable to fit your scenario. But you're definitely right on shortening it to KEY.

2022-08-05 20:26 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +While effective for occasional configuration, scripting of such commands requires clunky nesting within an SSH command.
I've done some funky ssh stuff, but not in the context of salt. @Pinna3 Do you have an example or know what Alan is referring to?

2022-08-05 20:31 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +    -d fun=test.ping
@Pinna3 can you grab this?

2022-08-05 20:32 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +$ salt <minion_id> test.ping
@Pinna3 can you grab this?

2022-08-05 20:53 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +Response:
It could, but I do like to keep commands and responses separate for clarity's sake.

2022-08-05 20:56 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +**Note:** `cmd.run_all` will provide a retcode for errors whereas `cmd.run` will not.
For the note, or for the script file?

2022-08-05 20:59 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +Now that you have a web API, you can automate the token reclamation and implement scripts across one or multiple masters.
@Pinna3 Do you have a script that you've written that has used this? Something we could pull from to form a simple example for automation?

2022-09-27 19:21 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +**Note:** `cmd.run_all` will provide a retcode for errors whereas `cmd.run` will not.
for the note
also add the note to the sentence above the it.

2022-09-27 19:22 UTC, alan-cugler commented
mike pinna removed accreditation

2022-09-27 19:23 UTC, alan-cugler commented
Lets add an example bash script of more than one master being called in cherrypy loop.

2022-09-28 21:04 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +$ salt <minion_id> test.ping
I'll grab these when Sam and I run through it.

2022-09-28 21:06 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +$ salt-call --local tls.create_self_signed_cert
Disclaimer that I didn't write this part, but it seems to me that this is targeting the salt master itself? Not clear on what salt-call local does myself, though, so Sam and I may have to try a more standard way (do you have a suggestion) when we go through it.

2022-09-28 21:06 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +$ passwd **saltdev**
Seems like it

2022-09-28 21:19 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +* `-d arg='bash /root/script.sh'` adds the argument 'bash /root/script.sh'
I think I've cleared this up.

2022-10-13 16:59 UTC, alan-cugler requested changes
Its looking usable

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +# Instruments of Choice
salt logo shouldnt be breaking the line horizon of the section header

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +Salt is a configuration management tool composed of salt masters and salt minions. This blog post assumes a basic knowledge of Salt fundamentals. For a brief overview of Salt, checkout their [docs](h
hugging the border to much

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +[CherryPy](https://docs.cherrypy.dev/en/latest/) is “a minimalist Python web framework.” For our use, we will be taking advantage of the [REST API](https://www.tutorialspoint.com/cherrypy/cherrypy_we
hugging the border to much

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +$ sudo salt <minion-2> test.ping
add a space between previous command result and new terminal command

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +@alan do you have any great examples of this nastiness?
https://github.com/terminal-labs/iac/blob/survival/origin/salt/srv/state1/ec2/salt.sls#L36 is the best I have, but the logic in that file is over several commands, so you could show all the commands in row? but I also think its reasonable to not demonstrate if it requires to much time to come up with something.

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +With CherryPy, once we have acquired a token we can directly execute or script any commands required.
so in comparison to my above link, can cherrypy deliver the script, change the permissions and then execute the file in one command? I suspect its the same amount of effort.

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +Perform these steps on each Salt Master where 54.221.182.205
whya are we giving an IP? `54.221.182.205`

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +CherryPy’s [PAM](https://en.wikipedia.org/wiki/Pluggable_authentication_module "Pluggable Authentication Module") authentication requires a non-root user. Add a user and password for API authenticati
add a note this isnt best practice for user settings

2022-10-13 16:59 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +    print(master.local_cmd("cmd.run_all", "bash /root/script.sh").json())
make this its own code block with appropriate refactoring, then demo running it and results coming back.

2022-10-14 13:46 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +Perform these steps on each Salt Master where 54.221.182.205
Whoops! Looks like I had a misplaced cursor sometime when I was testing. Rolled that back.

2022-10-14 15:15 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +    print(master.local_cmd("cmd.run_all", "bash /root/script.sh").json())
Had a go at this. Thoughts?

2022-10-14 15:25 UTC, BenjaminEchelmeier commented on content/blog/a-salty-api/contents.lr
> +With CherryPy, once we have acquired a token we can directly execute or script any commands required.
Yes. The use case here isn't to simplify running an ssh command on a minion, it's to simplify running commands on a master remotely.

2022-10-17 15:20 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +    print(master.local_cmd("cmd.run_all", "bash /root/script.sh").json())
lets change this to yaml output rather than json, and see how that looks. lets also change the minion names to something more generic but uniformed in the output

2022-10-17 15:21 UTC, alan-cugler commented on content/blog/a-salty-api/contents.lr
> +With CherryPy, once we have acquired a token we can directly execute or script any commands required.
lets remove as much comments and unnecessary QoL code in that script.

2022-10-17 18:31 UTC, alan-cugler approved these changes
Looks good to me, unless someone wants to tweak.

2022-10-17 20:14 UTC, nixjdm commented
This is confusing: ![Screenshot from 2022-10-17 15-05-02](https://user-images.githubusercontent.com/3431410/196272524-29103bcd-e6ce-49d8-b24d-c84b121342e8.png)

It makes it look like there's a root command when you really want a comment. I'll fix this. The syntax highlighting thinks the hash is the start of a root command, not a comment. Putting an additional `$ ` at the start of those lines will fix it.

Most often when I want commands in markdown, I'll looking for people to copy and paste the code, so I would use 

    ```shell

and not supply the $/# prompt you are. Here, supplying the prompt makes sense to differentiate it also from the return you're also showing.

2022-10-17 20:52 UTC, merged