Sam's bio and pic
terminal-labs/tl_web pull request #78
Opened 2022-10-21 19:05 UTC by srlt42

2022-12-12 16:21 UTC, BenjaminEchelmeier requested changes
I think I'd like to see a bit of a reformatting--clarify your paragraph divisions a bit? 
Something like:

1. Where I came from
2. What I do for fun
3. How I came to/why I do this work

2022-12-12 16:21 UTC, BenjaminEchelmeier commented on content/who-we-are/our-team/contents.lr
> +I was born in a small town in Missouri and was the youngest of 5, my oldest brother being 10 years older than me. As a result I was very young when he started getting into Engineering and that is wha
Science Olympiad, Math Relays, Scholar Bowl

2022-12-12 16:21 UTC, BenjaminEchelmeier commented on content/who-we-are/our-team/contents.lr
> +Existing in these kinds of circles led me to many of my other interests that still persist to this day. Things like theatre which I did for several years, or Dungeons and Dragons which to this day I
Could grow this a bit to include current hobbies?

2022-12-12 16:21 UTC, BenjaminEchelmeier commented on content/who-we-are/our-team/contents.lr
> +Eventually I went on to study at Missouri University of Science and Technology where my love of video games and internet culture led me to study computer science. There I made many of my closest frie
This paragraph is solid

2023-01-22 04:33 UTC, alan-cugler commented
I think its good!

2023-01-22 04:33 UTC, merged